"""Compatibility facade for deterministic fake-model helpers."""

from __future__ import annotations

from hardwise.workbench.chat_fake_client import (
    FakeWorkbenchAnthropic,
    _AuditedL78SnapshotCollection,
    _FakeWorkbenchMessages,
)
from hardwise.workbench.chat_fake_parsing import (
    _FakeResponse,
    _FakeTextBlock,
    _FakeToolUseBlock,
    _FakeUsage,
    _choose_refdes,
    _document_payload,
    _evidence_locator_payload,
    _is_evidence_chain_smoke,
    _locator_topic,
    _needs_datasheet_search,
    _needs_document_coverage,
    _needs_document_summary,
    _needs_evidence_locator,
    _parse_runner_prompt,
    _runner_prompt,
    _search_payload,
    _tool_payloads,
    _topology_payload,
    _topology_tool_uses,
    _validation_payload,
    _wants_english,
    _localized,
)
from hardwise.workbench.chat_fake_responses import (
    _evidence_from_checks,
    _important_checks,
    _row_evidence,
    _sanitize_chat_copy,
    _summarize_component_context_payload,
    _summarize_net_context_payload,
    _summarize_net_search_payload,
    _summarize_topology_payload,
    _trace_refdes,
)

C5_L2_SNAPSHOT_QUESTION = "查看 L7805 输入耐压的数据手册证据链"

__all__ = [
    "C5_L2_SNAPSHOT_QUESTION",
    "FakeWorkbenchAnthropic",
    "_AuditedL78SnapshotCollection",
    "_FakeWorkbenchMessages",
    "_FakeResponse",
    "_FakeTextBlock",
    "_FakeToolUseBlock",
    "_FakeUsage",
    "_choose_refdes",
    "_document_payload",
    "_evidence_locator_payload",
    "_is_evidence_chain_smoke",
    "_locator_topic",
    "_needs_datasheet_search",
    "_needs_document_coverage",
    "_needs_document_summary",
    "_needs_evidence_locator",
    "_parse_runner_prompt",
    "_runner_prompt",
    "_search_payload",
    "_tool_payloads",
    "_topology_payload",
    "_topology_tool_uses",
    "_validation_payload",
    "_wants_english",
    "_localized",
    "_evidence_from_checks",
    "_important_checks",
    "_row_evidence",
    "_sanitize_chat_copy",
    "_summarize_component_context_payload",
    "_summarize_net_context_payload",
    "_summarize_net_search_payload",
    "_summarize_topology_payload",
    "_trace_refdes",
]
