"""Document candidate and profile drafting commands."""

from __future__ import annotations

import re
from pathlib import Path

import typer

from hardwise.path_display import display_path

commands = typer.Typer()


@commands.command(name="build-document-index-candidates")
def build_document_index_candidates(
    validation_index: Path = typer.Argument(
        ...,
        help="Project validation index JSON generated by design-validator-ui --index-json.",
    ),
    output: Path | None = typer.Option(
        None,
        "--output",
        "-o",
        help="Output CSV path (default: reports/<index-stem>-document-candidates.csv).",
    ),
    families: list[str] | None = typer.Option(
        None,
        "--family",
        help="Only include candidate rows for this suggested family; may be repeated.",
    ),
    datasheets_com: bool = typer.Option(
        False,
        "--datasheets-com",
        help="Classify rows with Datasheets.com lookup; exact single MPN PDF hits are approved.",
    ),
    limit: int = typer.Option(
        5,
        "--limit",
        help="Datasheets.com search result limit when --datasheets-com is enabled (1-10).",
    ),
    timeout_seconds: int = typer.Option(
        20,
        "--timeout",
        help="Datasheets.com HTTP timeout in seconds when --datasheets-com is enabled.",
    ),
) -> None:
    """Write reviewable document-index candidate rows from grouped coverage."""

    from hardwise.documents import (
        DocumentCandidateError,
        build_document_candidate_report,
        render_document_candidate_csv,
    )

    lookup = _datasheets_com_candidate_lookup(
        datasheets_com,
        limit=limit,
        timeout_seconds=timeout_seconds,
    )

    try:
        report = build_document_candidate_report(
            validation_index,
            families=families,
            datasheets_com_lookup=lookup,
        )
    except DocumentCandidateError as e:
        typer.echo(f"error: document candidate generation failed: {e}", err=True)
        raise typer.Exit(1) from e

    if output is None:
        output = Path("reports") / f"{validation_index.stem}-document-candidates.csv"
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render_document_candidate_csv(report), encoding="utf-8")
    document_counts = {
        status: sum(row.document_status == status for row in report.candidates)
        for status in ("matched", "no_result", "ambiguous", "manual_needed")
    }
    approved = sum(row.review_status == "approved" for row in report.candidates)
    typer.echo(
        f"document-index-candidates: {output} "
        f"(groups={report.component_group_count}, candidates={len(report.candidates)}, "
        f"families={','.join(report.family_filter) if report.family_filter else 'all'}, "
        f"matched={document_counts['matched']}, "
        f"no_result={document_counts['no_result']}, "
        f"ambiguous={document_counts['ambiguous']}, "
        f"manual_needed={document_counts['manual_needed']}, "
        f"approved={approved}, "
        f"skipped_passive={report.skipped_passive}, "
        f"skipped_mechanical={report.skipped_mechanical}, "
        f"skipped_matched={report.skipped_matched_document}, "
        f"skipped_family_filter={report.skipped_family_filter})"
    )


def _datasheets_com_candidate_lookup(
    enabled: bool,
    *,
    limit: int,
    timeout_seconds: int,
):
    """Return a Datasheets.com lookup callback for candidate enrichment."""

    if not enabled:
        return None

    import os

    from dotenv import load_dotenv

    from hardwise.documents.datasheets_com import (
        DATASHEETS_COM_API_KEY_ENV,
        DATASHEETS_COM_API_KEY_ENV_LEGACY,
        lookup_datasheets_com,
    )

    if limit < 1 or limit > 10:
        typer.echo("error: --limit must be between 1 and 10", err=True)
        raise typer.Exit(1)
    if timeout_seconds < 1:
        typer.echo("error: --timeout must be >= 1", err=True)
        raise typer.Exit(1)
    load_dotenv(override=True)
    api_key = os.environ.get(DATASHEETS_COM_API_KEY_ENV) or os.environ.get(
        DATASHEETS_COM_API_KEY_ENV_LEGACY
    )
    if api_key == "replace_me":
        api_key = None

    def lookup(query: str):
        return lookup_datasheets_com(
            query,
            api_key=api_key,
            limit=limit,
            timeout_seconds=timeout_seconds,
        )

    return lookup


@commands.command(name="document-candidate-smoke")
def document_candidate_smoke(
    netlist_path: Path = typer.Argument(
        ...,
        help=(
            "Path to an Allegro/Telesis third-party ASCII netlist, or a Capture/Allegro PST input."
        ),
    ),
    bom_path: Path | None = typer.Argument(
        None,
        help=(
            "Path to a schematic-exported BOM file. If omitted, "
            "BOM candidates are auto-selected from an Allegro/PST project directory."
        ),
    ),
    profiles: Path = typer.Option(
        Path("data/datasheet_profiles"),
        "--profiles",
        help="Directory containing structured DatasheetProfile JSON files.",
    ),
    baseline_document_index: Path | None = typer.Option(
        None,
        "--document-index",
        help=(
            "Optional reviewed document index used for the baseline workbench context. "
            "Candidate CSV output remains separate."
        ),
    ),
    candidate_csv: Path | None = typer.Option(
        None,
        "--candidate-csv",
        help=(
            "Output candidate CSV path (default: reports/<project>-document-candidate-smoke.csv)."
        ),
    ),
    summary_json: Path | None = typer.Option(
        None,
        "--summary-json",
        help=(
            "Output smoke summary JSON path (default: reports/<candidate-csv-stem>-summary.json)."
        ),
    ),
    families: list[str] | None = typer.Option(
        None,
        "--family",
        help="Only include candidate rows for this suggested family; may be repeated.",
    ),
    datasheets_com: bool = typer.Option(
        False,
        "--datasheets-com",
        help="Classify rows with Datasheets.com lookup; exact single MPN PDF hits are approved.",
    ),
    limit: int = typer.Option(
        5,
        "--limit",
        help="Datasheets.com search result limit when --datasheets-com is enabled (1-10).",
    ),
    timeout_seconds: int = typer.Option(
        20,
        "--timeout",
        help="Datasheets.com HTTP timeout in seconds when --datasheets-com is enabled.",
    ),
) -> None:
    """Run document-candidate generation plus workbench queue projection smoke."""

    from hardwise.documents import (
        run_document_candidate_smoke,
        write_document_candidate_smoke_summary,
    )

    lookup = _datasheets_com_candidate_lookup(
        datasheets_com,
        limit=limit,
        timeout_seconds=timeout_seconds,
    )

    try:
        summary = run_document_candidate_smoke(
            netlist_path=netlist_path,
            bom_path=bom_path,
            profiles=profiles,
            baseline_document_index=baseline_document_index,
            candidate_csv=candidate_csv,
            families=families,
            datasheets_com_lookup=lookup,
            datasheets_com_enabled=datasheets_com,
        )
    except Exception as e:
        typer.echo(f"error: document candidate smoke failed: {type(e).__name__}: {e}", err=True)
        raise typer.Exit(1) from e

    if summary_json is None:
        candidate_path = Path(summary.candidate_csv)
        summary_json = candidate_path.with_name(f"{candidate_path.stem}-summary.json")
    write_document_candidate_smoke_summary(summary, summary_json)
    typer.echo(
        f"document-candidate-smoke: {summary_json} "
        f"(candidate_csv={summary.candidate_csv}, "
        f"candidates={summary.candidate_rows}, "
        f"approved={summary.candidate_approved}, "
        f"needs_review={summary.candidate_needs_review}, "
        f"rows_with_url={summary.candidate_rows_with_url}, "
        f"queue={summary.workbench_document_candidate_tasks}, "
        f"PASS/WARN/ERROR={summary.pass_count}/{summary.warn_count}/{summary.error_count}, "
        f"unchanged={summary.pass_warn_error_unchanged})"
    )


@commands.command(name="fetch-approved-documents")
def fetch_approved_documents_cmd(
    document_index: Path = typer.Argument(
        ...,
        help="Reviewed document-index CSV/TSV with direct public PDF URLs.",
    ),
    cache_dir: Path = typer.Option(
        Path("data/datasheets/cache"),
        "--cache-dir",
        help="Directory for SHA-addressed cached PDFs.",
    ),
    metadata: Path | None = typer.Option(
        Path("data/datasheets/documents.jsonl"),
        "--metadata",
        help="Append JSONL provenance records here.",
    ),
    no_metadata: bool = typer.Option(
        False,
        "--no-metadata",
        help="Do not write provenance JSONL records.",
    ),
    timeout_seconds: int = typer.Option(
        20,
        "--timeout",
        help="Per-document HTTP timeout in seconds.",
    ),
) -> None:
    """Fetch reviewed public datasheet PDFs into the local document cache."""

    from hardwise.documents import fetch_approved_documents, parse_document_index

    if timeout_seconds < 1:
        typer.echo("error: --timeout must be >= 1", err=True)
        raise typer.Exit(1)
    resolved_metadata = None if no_metadata else metadata

    try:
        index = parse_document_index(document_index)
        report = fetch_approved_documents(
            index,
            cache_dir,
            metadata_path=resolved_metadata,
            timeout_seconds=timeout_seconds,
        )
    except Exception as e:
        typer.echo(f"error: document fetch failed: {type(e).__name__}: {e}", err=True)
        raise typer.Exit(1) from e

    typer.echo(
        f"documents-fetch: {cache_dir} "
        f"(fetched={len(report.fetched)}, skipped={len(report.skipped)}, "
        f"metadata={display_path(resolved_metadata) if resolved_metadata else 'off'})"
    )
    for skipped in report.skipped[:5]:
        typer.echo(
            f"skip line {skipped.source_line}: {skipped.reason} ({skipped.title})",
            err=True,
        )


@commands.command(name="search-datasheets-com")
def search_datasheets_com_cmd(
    query: str = typer.Argument(..., help="MPN or part search query."),
    output: Path | None = typer.Option(
        None,
        "--output",
        "-o",
        help="Output reviewable document-index CSV path.",
    ),
    limit: int = typer.Option(
        5,
        "--limit",
        help="Maximum search results to request (1-10).",
    ),
    page: int = typer.Option(
        1,
        "--page",
        help="Search result page to request.",
    ),
    timeout_seconds: int = typer.Option(
        20,
        "--timeout",
        help="HTTP timeout in seconds.",
    ),
) -> None:
    """Search Datasheets.com and write candidate document-index rows."""

    import os

    from dotenv import load_dotenv

    from hardwise.documents.datasheets_com import (
        DATASHEETS_COM_API_KEY_ENV,
        DATASHEETS_COM_API_KEY_ENV_LEGACY,
        lookup_datasheets_com,
        render_datasheets_com_document_index_csv,
    )

    if limit < 1 or limit > 10:
        typer.echo("error: --limit must be between 1 and 10", err=True)
        raise typer.Exit(1)
    if page < 1:
        typer.echo("error: --page must be >= 1", err=True)
        raise typer.Exit(1)
    if timeout_seconds < 1:
        typer.echo("error: --timeout must be >= 1", err=True)
        raise typer.Exit(1)

    load_dotenv(override=True)
    api_key = os.environ.get(DATASHEETS_COM_API_KEY_ENV) or os.environ.get(
        DATASHEETS_COM_API_KEY_ENV_LEGACY
    )
    if api_key == "replace_me":
        api_key = None

    report = lookup_datasheets_com(
        query,
        api_key=api_key,
        limit=limit,
        page=page,
        timeout_seconds=timeout_seconds,
    )
    if report.status in {
        "not_configured",
        "rate_limited",
        "cloudflare_challenge",
        "provider_error",
    }:
        typer.echo(f"error: datasheets.com lookup failed: {report.status}", err=True)
        if report.reason:
            typer.echo(f"reason: {report.reason}", err=True)
        raise typer.Exit(1)

    if output is None:
        output = Path("reports") / f"{_safe_output_stem(query)}-datasheets-com-candidates.csv"
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render_datasheets_com_document_index_csv(report), encoding="utf-8")

    remaining = report.rate_limits.remaining_month
    remaining_text = f", remaining_month={remaining}" if remaining is not None else ""
    typer.echo(
        f"datasheets-com-lookup: {output} "
        f"(status={report.status}, results={len(report.results)}, "
        f"direct_pdfs={report.direct_datasheet_count}{remaining_text})"
    )


@commands.command(name="recommend-next-family")
def recommend_next_family(
    validation_index: Path = typer.Argument(
        ...,
        help="Project validation index JSON generated by design-validator-ui --index-json.",
    ),
    output: Path | None = typer.Option(
        None,
        "--output",
        "-o",
        help="Output Markdown path (default: reports/<index-stem>-next-family.md).",
    ),
) -> None:
    """Write advisory next-family recommendations from grouped coverage."""

    from hardwise.validation.coverage_priority import (
        CoveragePriorityError,
        build_family_coverage_report,
        render_family_coverage_markdown,
    )

    try:
        report = build_family_coverage_report(validation_index)
    except CoveragePriorityError as e:
        typer.echo(f"error: next-family recommendation failed: {e}", err=True)
        raise typer.Exit(1) from e

    if output is None:
        output = Path("reports") / f"{validation_index.stem}-next-family.md"
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render_family_coverage_markdown(report), encoding="utf-8")
    try_existing = sum(
        item.recommended_action == "try_existing_validator_profile"
        for item in report.recommendations
    )
    triage_new = sum(
        item.recommended_action == "triage_for_new_validator" for item in report.recommendations
    )
    typer.echo(
        f"next-family: {output} "
        f"(families={len(report.recommendations)}, "
        f"try_existing={try_existing}, triage_new={triage_new})"
    )


@commands.command(name="draft-datasheet-profile")
def draft_datasheet_profile(
    validation_index: Path = typer.Argument(
        ...,
        help="Project validation index JSON generated by design-validator-ui --index-json.",
    ),
    identity: str = typer.Option(
        ...,
        "--identity",
        help="Component group identity to draft, e.g. PCA9548APW.",
    ),
    document_index: Path | None = typer.Option(
        None,
        "--document-index",
        help="Optional reviewed document index CSV/TSV used to select the public document.",
    ),
    archetype: str | None = typer.Option(
        None,
        "--archetype",
        help="Optional needs-review profile archetype id, e.g. 74x165_piso_16pin.",
    ),
    evidence_chunks: Path | None = typer.Option(
        None,
        "--evidence-chunks",
        help="Optional PDF/HTML chunk JSONL used to attach datasheet page evidence tokens.",
    ),
    output: Path = typer.Option(
        ...,
        "--output",
        "-o",
        help="Output needs-review DatasheetProfile draft JSON path.",
    ),
) -> None:
    """Create a needs-review DatasheetProfile draft from grouped coverage."""

    from hardwise.ir.profile_draft import ProfileDraftError, draft_profile_from_project_index

    try:
        profile = draft_profile_from_project_index(
            validation_index,
            identity=identity,
            document_index_path=document_index,
            archetype_id=archetype,
            evidence_chunks_path=evidence_chunks,
        )
        profile.save(output)
    except ProfileDraftError as e:
        typer.echo(f"error: profile draft failed: {e}", err=True)
        raise typer.Exit(1) from e
    except Exception as e:
        typer.echo(f"error: profile draft failed: {type(e).__name__}: {e}", err=True)
        raise typer.Exit(1) from e

    typer.echo(
        f"profile-draft: {output} "
        f"(part_number={profile.part_number}, review_status={profile.review_status}"
        f"{', archetype=' + archetype if archetype else ''}"
        f"{', evidence_chunks=on' if evidence_chunks else ''})"
    )


def _safe_output_stem(value: str) -> str:
    """Return a conservative filesystem stem for generated report paths."""

    stem = re.sub(r"[^A-Za-z0-9._-]+", "-", value.strip()).strip("-._")
    return stem.lower() or "datasheets-com"


def register_commands(app: typer.Typer) -> None:
    """Register this command group on the root CLI app."""
    app.registered_commands.extend(commands.registered_commands)
